spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: [client-id]
            clientSecret: [client.secret]
  jpa:
    hibernate:
      ddl-auto: "update"
  datasource:
    url: [mysql-url]
    username: [mysql-username]
    password: [mysql-password]
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  output:
    ansi:
      enabled: "DETECT"