spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: [issuer-uri]
          jwk-set-uri:  [jwk-set-uri]
  jpa:
    hibernate:
      ddl-auto: "update"
  datasource:
    url: [mysql-url]
    username: [mysql-username]
    password: [mysql-password]
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  output:
    ansi:
      enabled: "DETECT"
oauth2:
  audience: [audience]