name: create-release
on:
  workflow_run:
    workflows: ["run-tests"]
    types:
      - completed
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      version: ${{env.version}}
      tagexists: ${{ steps.tagexists.outputs.exists }}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Set Up JDK 17 for building project
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Make Maven-Wrapper executable
        run: chmod +x ./mvnw
      - name: Setup Node for Semantic release
          uses: actions/setup-node@v3
          with:
            node-version: 16.x
            cache: 'npm'
      - name: Install Semantic Relase and plugins
        run: npm i -g semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/exec @semantic-release/github @smeantic-release/git
      - name: Run semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
        run: npx semantic-release