name: Create release
on:
  push:
    branches: [main]

  jobs:
    build:
      runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make Maven-Wrapper executable
        run: chmod +x ./mvnw
      - name: Build project
        run: ./mvnw --batch-mode --update-snapshots -D gpg.skip=true verify
    release-latest:
      runs-on: ubuntu-latest
      needs: build
    steps:
      - name: Create 'latest' release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "./target/todolistapi.jar"
          generateReleaseNotes: true
          commit: "main"
          tag: "latest"
          token: ${{ secrets.GITHUB_TOKEN }}
    release-version:
      if: true
      runs-on: ubuntu-latest
      needs: build
    steps:
      - name: Get project version
        run: |
          echo "VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)"
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: false
          bodyFile: "./target/todolistapi.jar"
          generateReleaseNotes: true
          commit: "main"
          tag: "v${{env.VERSION}}""
          token: ${{ secrets.GITHUB_TOKEN }}