name: create-release
on:
  workflow_run:
    workflows: ["run-tests"]
    types:
      - completed
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      version: ${{env.version}}
      tagexists: ${{ steps.tagexists.outputs.exists }}
    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Make Maven-Wrapper executable
        run: chmod +x ./mvnw
      - name: Build project
        run: ./mvnw --batch-mode -DskipTests clean package
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: ./target/todolistapi.jar
      - name: Get project version
        id: fetchversion
        run: |
          echo "version=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)"  >> $GITHUB_ENV
      - name: Check if release for version already exists
        uses: mukunku/tag-exists-action@v1.0.0
        id: tagexists
        with:
          tag: 'v${{env.version}}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-version:
    needs: build
    runs-on: ubuntu-latest
    if: needs.build.outputs.tagexists == 'false'
    steps:
      - name: Download jar
        uses: actions/download-artifact@v3
        with:
          name: jar
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: false
          artifacts: "todolistapi.jar"
          name: "TodolistApi v${{needs.build.outputs.version}}"
          generateReleaseNotes: true
          commit: "main"
          tag: "v${{needs.build.outputs.version}}"
          token: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
