name: Build and publish Docker image
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . -t ${{secrets.DOCKER_USERNAME}}/todolistapi:${{ github.event.release.tag_name }}
      - name: Login to Docker
        run: docker login -u ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}
      - name: Push image (version tag)
        run: docker push ${{secrets.DOCKER_USERNAME}}/todolistapi:${{ github.event.release.tag_name }}
      - name: Push image (latest tag)
        run: docker push ${{secrets.DOCKER_USERNAME}}/todolistapi:latest
      - name: Be happy that everything worked
        run: echo Woohoo!
