name: Build and publish Docker image
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get all relevant tags
        uses: jupyterhub/action-major-minor-tag-calculator@v1
        id: gettags
        with:
          githubToken: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
          prefix: "${{secrets.DOCKER_USERNAME}}/todolistapi:"
          branchRegex: "^[^/]+$"
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build, tag and push images
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ join(fromJson(steps.gettags.outputs.tags)) }}
